- bloom/commands/git/release.py
- bloom/config.py
- bloom/generators/common.py
- bloom/generators/debian/generate_cmd.py
- bloom/generators/debian/generator.py
- bloom/generators/rpm/generate_cmd.py
- bloom/generators/rpm/generator.py
- test/system_tests/common.py
Groovy is not even supported anymore so we might as well propose
the latest official release
> replace groovy by indigo in many default values

- bloom/commands/git/import_upstream.py
- bloom/commands/git/patch/rebase_cmd.py
- test/system_tests/test_catkin_release.py
> Addresses issue with white space in file names of upstream repository

- bloom/generators/debian/generator.py
> debian: check for missing rosdep keys all at once

- bloom/commands/release.py
- bloom/config.py
- bloom/git.py
> address error when running in git with multiple remotes

- bloom/commands/git/__init__.py
- bloom/commands/git/branch.py
- bloom/commands/git/config.py
- bloom/commands/git/generate.py
- bloom/commands/git/import_upstream.py
- bloom/commands/git/release.py
- bloom/commands/release.py
- bloom/generators/debian/generator.py
- bloom/generators/rpm/generator.py
This adjusts code to conform to the new pep8 module update which has a stricter E402 check.
> Fixup tests

- bloom/generators/debian/generator.py
- bloom/generators/rpm/generator.py
that patch works for me for naoqi_bridge
I don't understand why the package variable is even used, it's part of the previous loop.
> fix bad handling of conflicts/replaces

- bloom/util.py
> set LC_ALL to C when running git

- bloom/commands/release.py
- bloom/github.py
Also fixed when creating a rosdistro fork with a different name.
> Fixing detection of rosdistro user fork when trying to create a pull request

- bloom/commands/release.py
- bloom/github.py
Fixes #388
HTTPSConnection is not aware of Proxy Servers like urllib.
Refactored github.py to use urllib similar to util.py.
> Enable use behind proxy servers

- bloom/git.py
This makes bloom work for me on git 2.9.3
Connects to #398
> Support 'working tree clean' output from git

- bloom/commands/release.py
This will hopefully help increase usage of PR testing.
> add a prompt in bloom to ask if the maintainer would like to enable pull request testing

- bloom/commands/release.py
See: https://github.com/ros-infrastructure/bloom/pull/418#discussion_r108278331
> fix default answer for pull request testing

- bloom/commands/release.py
rep 141 defines developed, maintaned, unmaintaned and end-of-life
http://www.ros.org/reps/rep-0141.html#distribution-file
> add missing 'unmaintaned' status

- bloom/generators/debian/generator.py
This looks like it was just a copy-paste error.
> Fix incorrect package name in error message.

- CHANGELOG.rst
- bloom/generators/release.py
- setup.py
- stdeb.cfg
Preparing for 0.6 release of bloom.
> Prepare release 0.6.0

- bloom/generators/rosdebian.py
This is the one change to bloom itself required to release packages for ardent.
@wjwwood I'd like to get this into a bloom release later today. 🙇
> Insert ros_workspace package for ardent releases.

- bloom/commands/release.py
One small change that has always bugged me: This PR makes the track command line argument optional, and if it is not set, it sets it to the rosdistro.
> Optional track

- bloom/generators/rosdebian.py
Bouncy Bolson will be the next ROS 2 release! 🐢🐢
> Add bouncy to the list of rosdistros to get the workspace shim.

- bloom/util.py
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Add melodic to the list of bloom distros.

- bloom/generators/rosdebian.py
In order to build packages which support but do not require all rmw providers we need to prevent them from being required by end users but make sure that they're installed on the buildfarm when any message package is built.
To avoid needing to apply these changes manually we've added another ROS 2-specific behavior to bloom.
The new behavior looks at group membership and adds vendor typesupport packages to the build (but not runtime or build export) dependencies of the packages in the rosidl_interface_packages group.
> Inject vendor typesupport packages at build time for ROS 2.

- CHANGELOG.rst
- setup.py
This is a small follow up release to #476. PR is opened for visibility as I'll be merging the release forthwith.
> Prepare 0.6.6

- bloom/commands/release.py
Related to #496.
When checking recent distros for information about a repository only consider distros with the same type.
Tested with a locally modified `rosdistro` database. E.g. adding a ROS 2 distro with a unique repo name and then trying to do a release of that repo into a ROS 1 distro. Without this patch `bloom` would use the existing ROS 2 info as a suggestion for the ROS 1 release.
This will enable merging the two `rosdistro` databases without a side effect to users when using `bloom`.
> only consider same type distros when looking for repo name in recent distros

- CHANGELOG.rst
- setup.py
This commit will be fast-forwarded onto master.
We'll get a follow up release going with the GitLab support and #502
> Prepare 0.7.0

- bloom/commands/release.py
I was using #489 but clearly my local copy was dirty.These two changes fix the regression tagged #504 and fix the pull request creation unicode handling in python2.
> Fix a couple bugs from the python3 compatibility PR.

- CHANGELOG.rst
- setup.py
A small release to patch some bugs. This commit will be fast-forwarded onto master.
> Prepare 0.7.1

- bloom/generators/debian/generator.py
This patch enables to place files in the debian folder of the upstream repository.
Currently it's possible to place additional files into that folder. However if the file is present in the bloom template set (like rules.em) that file is overwritten.
See #507.
> Do not overwrite template files, if they exist

- bloom/generators/rpm/generator.py
Tested as working on hybrid package [`ml_classifiers`](https://github.com/astuff/ml_classifiers).
> Applying changes to rpm/generator.py suggested by @AAlon.

- bloom/util.py
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>
> Fix typo in util.py

- CHANGELOG.rst
- setup.py
Changes in this release: https://github.com/ros-infrastructure/bloom/compare/0.9.1..6d7b521
> Prepare 0.9.2

- bloom/commands/git/release.py
This adds a noninteractive option to git-bloom-release. Most of the time
this command is often non-interactive but several fields in the bloom
config can be set to :{ask} which would normally block with a prompt.
With this patch an error message will be raised instead if the :{ask}
option is used.
> Add non-interactive option to git-bloom-release command.

- bloom/generators/rpm/templates/ament_cmake/template.spec.em
- bloom/generators/rpm/templates/ament_python/template.spec.em
- bloom/generators/rpm/templates/cmake/template.spec.em
This is a bit primitive, but gets things moving.
> Run tests in RPM builds for ament and cmake packages

- bloom/generators/rpm/generator.py
The remove function on a Python list only removes the first occurrence of an element. Since we're going to convert the target list to a set later anyway, just make it a set to start with, eliminating the possibility that an element will appear more than once.
Follow-up to #602
> Handle skipping keys multiple times

- bloom/commands/release.py
Resolves #593 
Please review closely as this is my first time looking at bloom source and wasn't sure how to run/test it from the source.
> Don't prompt if --override-release-repository-url

- README.rst
> readme: update documentation link

- bloom/config.py
- bloom/generators/debian/generate_cmd.py
- bloom/generators/rosdebian.py
- bloom/generators/rosrelease.py
- bloom/generators/rosrpm.py
- bloom/generators/rpm/generate_cmd.py
- bloom/rosdistro_api.py
- bloom/util.py
This is an alternative to #663 as suggested by @nuclearsandwich.
Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>
> Get non eol distros from rosdistro index

- .github/workflows/ci.yaml
- .github/workflows/scheduled.yaml
Restores d3d21ae9e816500154798d254422ac30e6bbee0f after it was dropped as part of 058666e330c05ac7458ac9c33a62edeff278c115.
> Restore weekly CI job

- setup.py
> Drop support for Python <2.7, simplify setup.py
