bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

Three things:
1. Fixed another changelog sort issue in the RPM generator (present in `jsk_model_tools`)
2. Applied @wjwwood's rosdep key patch to the RPM generator
3. Fixed the `rosdep` key patch exit code as to not break https://github.com/ros-infrastructure/bloom/pull/308, which relies on a specific exit code indicating a `rosdep` key issue.

RPM fixes as well as key error recovery fix

---

bloom/generators/debian/generator.py
test/unit_tests/test_generators/test_debian/test_generator.py

Small change that formats the text in the `Description` field of the `control` file such that the first sentence will be treated as the synopsis (or short description) by `apt` and related tools. The rest of the package description is added as a single, large paragraph (as it is now).
All nose tests still pass, and I've added some new ones.
A more fancy version of `format_description()` could perform a proper conversion of embedded newlines or `<p>` tags in package descriptions, but I thought to start with this first.
Context: [Support for 'short description' in package.xml / Bloom?](http://answers.ros.org/question/112886/support-for-short-description-in-packagexml-bloom/).

Extend debian generator to split pkg description into <synopsis, long description>

---

bloom/commands/release.py

There's some disagreement about list formatting, as [discussed here](http://spec.commonmark.org/0.20/#lists). In a nutshell, Bitbucket follows the Markdown.pl style, whereas Github follows CommonMark.
This change makes the output render more nicely on both platforms.

Add linebreaks to the generated README markdown

---

bloom/generators/debian/templates/control.em

If you do:
```
git clone git@github.com:ros-naoqi/naoqi_bridge-release.git
git checkout debian/ros-jade-naoqi-driver_0.4.7-0_vivid
git-buildpackage -uc -us --git-ignore-branch --git-ignore-new
```
You get this warning during the build:
```
dpkg-gencontrol: warning: unknown information field 'Conflicts' in input data in general section of control info file
```
And indeed:
```
dpkg -I ../ros-jade-naoqi-driver_0.4.7-0vivid_amd64.deb
```
does not show any conflicts info.
Nothing bad, it's just that the generated package will not conflict / replace what you want. This fixes it.

put the Conflicts and Replaces fields in the nongeneraal section

---

bloom/generators/rpm/templates/template.spec.em

This will only affect those `CMakeLists.txt` which use `GNUInstallDirs`.
This is breaking `fcl` on Fedora, because `libccd` (which is already a Fedora package, by the way) is getting installed to `/opt/ros/foo/lib64` on `x86_64` systems. This is incorrect, as ROS *always* uses `/opt/ros/foo/lib` on all architectures.

Manually specify lib dir in RPM spec file

---

bloom/config.py
bloom/generators/debian/generator.py

They will fail gracefully for the older rosdistros which do not have debian platform targets.
As we discussed with @wjwwood [from notes](https://github.com/ros/rosdistro/pull/10621#issuecomment-192541582)
I'd like to parameterize the default actions template on the rosdistro, but that is a much more effort. It will work for now but we will reencounter this any time we add or remove a supported platform. And this will cause indigo and jade instances of bloom to recommend updating the tracks even though they don't need it. 
I've tested this with a Kinetic gbp and it generates the debian targets. And on an indigo track it updates the track and skips the debian targets.

add building of debian platforms to the default actions

---

bloom/config.py

See: https://github.com/ros-infrastructure/bloom/pull/380#issuecomment-192552658
This is a diff of me testing it on my fork of `rviz-release`: https://github.com/wjwwood/rviz-release/commit/e86f9e27756b48dea5a5f96040ce3d5ec54a4259

use safe_dump for writing tracks to avoid unicode tags

---

bloom/generators/debian/generator.py

See: https://github.com/ros-infrastructure/bloom/pull/384

allow unicode in the long part of the description

---

bloom/generators/rpm/generator.py

releasing moveit just now, we were confused in bloom thinking we couldn't continue since ``libfcl-dev`` is not available in Fedora:
```
Failed to resolve libfcl-dev on fedora:23 with: Error running generator: Failed to resolve rosdep key 'libfcl-dev', aborting.
libfcl-dev is depended on by these packages: ['moveit_core']
<== Failed
Could not resolve rosdep key 'libfcl-dev' for distro '24':
No definition of [libfcl-dev] for OS [fedora]
rosdep key : libfcl-dev
OS name    : fedora
OS version : 24
Data: arch:
- fcl
debian:
- libfcl-0.5-dev
ubuntu:
- libfcl-0.5-dev
Failed to resolve libfcl-dev on fedora:24 with: Error running generator: Failed to resolve rosdep key 'libfcl-dev', aborting.
libfcl-dev is depended on by these packages: ['moveit_core']
<== Failed
Some of the dependencies for …
```

Make it clearer that fedora can be skipped

---

bloom/commands/release.py

This pull request fixes a crash when bloom-release tries to issue a PR to a forked rosdistro repository which belongs to the user:
```
Would you like to add documentation information for this repository? [Y/n]? n
Would you like to add source information for this repository? [Y/n]? n
Would you like to add a maintenance status for this repository? [Y/n]? n
Unified diff for the ROS distro file located at '/tmp/tmp_CLz5b/catkin-0.7.4-9.patch':
--- 93c8ea127b9356f887282b0b7353edd138528024/minimalist/distribution.yaml
+++ 93c8ea127b9356f887282b0b7353edd138528024/minimalist/distribution.yaml
@@ -19,7 +19,7 @@
tags:
release: release/minimalist/{package}/{version}
url: https://github.com/gdlg/catkin-release.git
-      version: 0.7.4-6
+      version: 0.7.4-9
cmake_modules:
release:
tags:
Traceback …
```

Fix PR fail to forked rosdistro repository

---

bloom/generators/debian/templates/source/options.em

This is a replacement for: https://github.com/ros-infrastructure/ros_buildfarm/pull/395 which is more cross platform.
e.g: https://github.com/ros-infrastructure/ros_buildfarm/pull/397 and https://github.com/ros-infrastructure/ros_buildfarm/pull/398
I ran a test release and the results ended up here: https://github.com/tfoote/test-gbp/blob/debian/kinetic/jessie/tf2_ros/debian/source/options

add auto-commit for quilt builds

---

bloom/util.py

I don't know if there is a way to efficiently get the list of active distro that doesn't imply getting + parsing the rosdistro index file. So this temporary solution updates the prompted list of distributions to match the active ros distros as of May 2017

update prompted distro list

---

bloom/commands/release.py

Running `bloom-release rviz --track kinetic --rosdistro kinetic` I had to pause for a minute when it asked if I wanted to open a PR from 'rosdistro/rosdistro:bloom-rviz-0' instead of my fork. This changes to what should be the correct prompt.
```
==> Checking on GitHub for a fork to make the pull request from...
==> Using this fork to make a pull request from: dhood/rosdistro
==> Cloning dhood/rosdistro...
==> mkdir -p rosdistro
==> git init
Initialized empty Git repository in /tmp/qzVe9B/rosdistro/.git/
Pull Request Title: rviz: 1.12.11-0 in 'kinetic/distribution.yaml' [bloom]
Pull Request Body : 
Increasing version of package(s) in repository `rviz` to `1.12.11-0`:
- upstream repository: https://github.com/ros-visualization/rviz.git
- release repository: …
```

Correct prompt for opening a pull request when using fork

---

bloom/commands/git/import_upstream.py
bloom/generators/debian/generator.py

https://github.com/ros-infrastructure/bloom/commit/1f164c156bf1e3b8b4ae1ea053a16c74ade066c1 is focused on git-bloom-import-upstream and https://github.com/ros-infrastructure/bloom/commit/442b4f8a2f49f969d10feaae18182529f1cae31e contains fixes for the Debian generator. Both are tested with python versions
- 2.7.12
- 3.5.2
The test source repository was https://github.com/eProsima/Fast-RTPS and release repository https://github.com/ros2-gbp/fastrtps-release.
If @wjwwood or @mikaelarguedas knows of any ROS kinetic or lunar packages that have utf-8 characters in the upstream or patched in package.xml template I would love to test this explicitly against them too.
I'm pretty sure the way I'm handling some of the py2/3 encoding cases could be improved upon and standardized throughout bloom, but …

Handle utf-8 in more cases.

---

bloom/commands/update.py

Otherwise I get:
> Error fetching latest version: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

use https rather than http to query pypi

---

bloom/generators/debian/generate_cmd.py
bloom/generators/rpm/generate_cmd.py

The separate build types pull request (#435) changed the internal API
for the place_template_files function, adding a required build_type
parameter.
A grep through the bloom codebase did not turn up anywhere else that I missed updating function invocations.
🔧 fixes #439

Pass package build type through generate command.

---

bloom/github.py

Fixes an import failure preventing `bloom-release --version` (and likely other things) from being run on python 3.
Found when smoke testing bloom 0.6.0.

Fix python 2/3 import compatibility.

---

CHANGELOG.rst
setup.py

Updates CHANGELOG and setup.py for 0.6.1.
🚧 When ready, squash all changes into a single commit with message `0.6.1` and rebase or fast-forward directly onto master.
Includes
- #438 
- #440 
- #441

Prepare 0.6.1 release.

---

setup.py

setup.py: find_package(exclude['test']) was not enough to exclude all
of the test packages bloom uses, there are a lot of subpackages (test.*)
that were not being caught and thus were being installed in
site-packages.

Fix setuptools test.* package pollution

---

bloom/commands/release.py
bloom/github.py

This is a proposed fix for #448.
A detailed outline of the code paths is present in that issue.
The error interface appears to have changed since the original code was written.
This adds code to handle the new error interface while preserving the old code.
It's possible this old code is no longer used and can be removed but I wouldn't know how to tell since #448 surfaces for me using both Python 2 and Python 3.

GitHub PR auth prompt fixes

---

bloom/github.py

json.loads excepts a string, but resp.read() returns a bytes object in
Python3. Added a helper function to try to detect the encoding of the
response, and use that to decode the bytes to str.
Tested this briefly with Python2 to make sure it wasn't broken. Tried to make it compatible.

Fixed python3 bloom-release, json.loads encoding

---

bloom/commands/export_upstream.py
bloom/git.py

although it seems this error was not even triggered before...
In any case releasing an upstream repo with submodules works with
https://github.com/vcstools/vcstools/pull/130
With the vcstools fix, we should be able to close https://github.com/ros-infrastructure/bloom/issues/217
At least it worked for me...

don't error if git repo has submodules

---

bloom/commands/release.py

* Enables the use of a new environment variable `BLOOM_RELEASE_REPO_BASE`. 
* This can be used instead of manually inputting the release repo url. 
* If the environment var exists, and `BLOOM_RELEASE_REPO_BASE` + repository + '-release.git' exists as a repository, then it will use that as the release repo.
* For example, all my release repos are over at `https://github.com/wu-robotics/` so if I set that as my environment variable, I can create a `bloom-example-release` repo there, and then if I try to `bloom-release` a package called `bloom-example`, it will automagically use that as my release repo.

RELEASE REPO BASE env var

---

bloom/generators/rpm/generator.py

Found this one while releasing random_numbers 0.3.2 for Melodic. I just copied the fix applied to the Debian generator to the rpm one.

Fix encoding issue when processing rpm templates.

---

bloom/commands/release.py

I missed remarking upon the dependency introduction when reviewing #460. This replaces the use of requests with standard library http handling.
Requests is a phenomenal library and I can definitely see bloom adopting its use in the future but I'd rather make that decision intentionally rather than in a minor release.
Fixes #467.

Remove unexamined dependency on requests.

---

bloom/commands/release.py

to avoid confusing error message like `A previous distribution, 'melodic', released this repository.`
as 'previous distribution' here doesnt refer to an 'older' distro but the most recent distro where a release of that repo has been made.

use the wording 'different' from above to avoid confusion

---

.travis.yml

Current versions of Python: https://devguide.python.org/#branchstatus
Python 3.3 reached its end of life last year.

Test on Python 3.4 and 3.6 because 3.3 is EOL

---

bloom/generators/rosdebian.py

The additional rmw implementation packages need to be present at build time for vendor
typesupport to be configured properly.
Follow up to #475.

Add rmw implementations to vendor typesupport build dependencies.

---

LICENSE.txt

I'm no pro at license structure but it seems to be convention in our other projects to update the copyright year with the most recent year changes have been made.
Since we're going to start distributing the license in deb packages (#470) it made sense to me to make sure that license info was up to date.
Obligatory: I am not a lawyer

Update copyright info and date.

---

stdeb.cfg

stdeb will install it in the debian way when referenced here.

Reference the LICENSE.txt from the stdeb.cfg

---

bloom/commands/git/release.py
bloom/commands/release.py

If `:{ask}` is specified for the release tag, the upstream tag is not written into the release repository, making it quite difficult to figure out what tag was used. This PR ensures that it is written into `tracks.yaml`.

Upstream Tag

---

bloom/commands/release.py

In order to make #458 easier to merge, I've made this branch which just reorders some of the core commands such that 
* The content for the PR is created first, followed by the github specific logic.
* The github is hidden behind a `if True` block, so that future whitespace changes are not needed. 
Let me know if this helps @nuclearsandwich

Reorder commands (toward Gitlab compatibility)

---

CHANGELOG.rst
setup.py

PR opened for visibility. This commit will be fast-forwarded directly onto master.
Changes:
*    Added debian/copyright file to debian package when license file is specified in package.xml. #470
*   Refactored release command to prepare for GitLab pull request support. #483
*   Fixed outdated GitHub URL in help text. #484
*   Added entry to tracks.yaml to store the upstream tag of the last release. #472
With thanks to @DLu, @otamachan, and @wjwwood for their contributions and review. :balloon:

Prepare release of 0.6.7.

---

test/system_tests/test_bloom_release.py

Add a very basic "smoke test" for syntax issues in the bloom-release command.

Add smoke test for `bloom-release -h`.

---

bloom/generators/rosdebian.py

This adds Crystal to the list of ROS 2 distros. I have #496 logged to reduce the need for hard-coded rosdistro names using the index v4 changes but this will get us releasing for crystal now.

Add crystal to list of ros2 distros with special handling.

---

bloom/commands/release.py
bloom/github.py

Supercedes #481 to fix GitHub pull request generation on Python3.
@allenh1 can you give this a whirl when you have a chance and see if it works for you. I've got it generating pull requests in a test environment from both python3 and python2.

Fix python 3 support for pull request generation.

---

bloom/commands/git/patch/trim_cmd.py
bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

In some places we were quoting removed files and in others we weren't. I did a grep through the codebase for `rm -rf` to catch the case mentioned in #450 as well as potentially others in the template file names.
Resolves #450.

Quote files removed with `git rm -rf`.

---

test/system_tests/test_catkin_release.py

With https://github.com/ros-infrastructure/rosdep/pull/647 rosdistros
that are no longer supported don't have rosdep updates fetched.
The system tests relied on groovy updates from rosdep. I've moved the
system test to melodic. I chose melodic rather than indigo or kinetic
because indigo will enter end-of-support later this year and Kinetic is
currently supported on only one Debian/Ubuntu distro. Melodic is still
supported on Bionic and Stretch.
Fixes #509 (hopefully)

Update the catkin release test to use melodic.

---

bloom/commands/release.py
bloom/config.py

The patch only updates the invocation where untrusted sources are being processed.

use yaml.safe_load for untrusted yaml input

---

setup.py
stdeb.cfg

As of 0.15.0 rosdep evaluates package format 3 conditions before resolving dependencies (https://github.com/ros-infrastructure/rosdep/pull/654). In order for bloom to support them as well it needs that version of rosdep.

Require rosdep 0.15.0 in order to handle conditions in dependencies.

---

stdeb.cfg

Closes a packaging regression on platforms no longer supported by
current rosdistro releases.
As of https://github.com/ros-infrastructure/bloom/pull/493 (first released in 0.6.8) we're relying on a version of rosdistro which is not supported by older Ubuntu and Debian releases (https://github.com/ros-infrastructure/rosdistro/pull/123). A recent release of rosdep [brought the issue to our attention](https://discourse.ros.org/t/rosdep-and-eol-distros/7640).
In addition to this change for future releases, the 0.6.8, 0.6.9, 0.7.0, 0.7.1, and 0.7.2 releases will be yanked from the platforms removed below to fix the regression.

Only release on platforms supported by rosdistro 0.7.0.

---

.travis.yml
test/__init__.py

This removes the environmental requirement that Git be configured prior to running the tests.
Git environment variable documentation: https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

Set Git author/committer within tests

---

test/unit_tests/test_packages.py

This is never encountered on Travis, but this test assumes that the CWD is a git repository.

Make tests runnable outside of a git repository

---

bloom/github.py

Otherwise you get an error like this:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/bloom/commands/release.py", line 1323, in perform_release
track, repository, distro, interactive, override_release_repository_url
File "/usr/local/lib/python3.7/site-packages/bloom/commands/release.py", line 867, in open_pull_request
gh = get_github_interface()
File "/usr/local/lib/python3.7/site-packages/bloom/commands/release.py", line 759, in get_github_interface
gh = Github(username, auth=auth_header_from_basic_auth(username, password))
File "/usr/local/lib/python3.7/site-packages/bloom/github.py", line 65, in auth_header_from_basic_auth
return "Basic {0}".format(base64.b64encode('{0}:{1}'.format(user, password)))
File …
```

fix str vs bytes issue in python3

---

bloom/generators/common.py
bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

Noodling on this approach in order to try and unblock @AAlon.
Quite aside from the clear need to factor the condition check into a function, a few other things stand out as worth considering before merging:
* For consistent results, maybe we could get our context from the bloom tracks.yaml rather than the environment
* I used comprehensions to filter conditions on lists of dependencies roughly in place but it's worth looking more closely (at a better time of day) to see if there's any reason not to check the evaluated conditions lazily after the list of keys to evaluate is generated rather than doing it on each list as its constructed.
An additional TODO is to check that the build_type condition is also checked and honored.

Evaluate dependency conditions

---

bloom/commands/git/release.py
bloom/config.py
test/system_tests/test_catkin_release.py

Per discussion in https://github.com/ros-infrastructure/bloom/pull/409
This is what most distributions default to and expect.

Start release increment at 1.

---

CHANGELOG.rst
setup.py

Using the branch to confirm with the release with CI. Rather than merging via the GitHub web UI this commit should be fast-forwarded onto the `master` branch.

Prepare 0.8.0

---

bloom/generators/debian/templates/ament_cmake/control.em
bloom/generators/debian/templates/ament_python/control.em
bloom/generators/debian/templates/catkin/control.em
bloom/generators/debian/templates/cmake/control.em

Since Debian Policy 4.0.1, the 'extra' Priority has been deprecated in favor of 'optional'. Continuing to issue 'extra' results in lintian warnings. Time to change!
https://lintian.debian.org/tags/priority-extra-is-replaced-by-priority-optional.html
This PR should probably be squashed for merge. Thanks!

Move to 'optional' Priority from 'extra', per Debian Policy 4.0.1

---

bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

Each commit message contains justification for the change.

Modernize RPM spec file templates

---

bloom/generators/rpm/generator.py

The SCM plugin for mock will create an archive of the sources if either this marker file is present in the root of the project or the `write_tar` option is specified in mock's configuration.
The way bloom works, we always want to archive the sources, but this isn't the default configuration of the SCM plugin. Writing this marker file means one less configuration is necessary when consuming the
release repo to build the RPMs with mock.
More info: https://fedoraproject.org/wiki/Projects/Mock/Plugin/Scm#Tar_file

Always create archive of sources when building RPM

---

bloom/commands/release.py

The goal of the variable is to avoid the steps of generating and pushing the PR with changes to rosdistro.
Not usual for catkin packages but we have use cases where we use bloom to generate the metadata and use `build.osrfoundation.org` to build packages that can not go into rosdistro index.

Support for BLOOM_NO_ROSDISTRO_PULL_REQUEST environment variable

---

bloom/generators/common.py
bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

Closes #536 with some improved error messaging and behavior.
1. In order to release packages with format 3 package.xml files, a v4 rosdistro index is required to provide sufficient context for evaluating package conditions.
To make it clearer that the problem is the index version and not an invalid / unknown distribution_type, an explicit version check and dedicated error message has been added.
2. For package formats 1 and 2 conditions are evaluated with an empty context so that downstream code will correctly see all fields without conditions as True.

Improve error handling for package conditions and index files.

---

stdeb.cfg

Specifically removes Trusty, Utopic, Vivid, and Wily and adds Cosmic, Disco, and Eoan.

Update suites to remove those older than xenial and add new ones.

---

bloom/commands/release.py
test/system_tests/test_bloom_setup.py

As neither of these situations require unsafe usage of YAML we should be
able to use the safe loader.

Use yaml.safe_load.

---

bloom/generators/common.py
bloom/rosdistro_api.py
setup.py
stdeb.cfg

The ROS_PYTHON_VERSION conditional is referenced in [REP-149](https://www.ros.org/reps/rep-0149.html) as a standard mechanism for determining the python major version used within a ROS workspace. For most ROS tools, package conditions can be taken from the local environment but Bloom has a different role: generating platform specific release information from a developer's workstation which may not match the targeted platforms. As with #519, bloom does not take package conditions from the local environment but instead from the distribution configuration. To support this both here and in other tools, [REP-153](https://www.ros.org/reps/rep-0153.html) was amended (see https://github.com/ros-infrastructure/rep/pull/207) to include a `python_version` field in the distribution information. Bloom …

Add ROS_PYTHON_VERSION to dependency conditionals.

---

bloom/commands/git/import_upstream.py
test/system_tests/test_catkin_release.py

Avoids backtraces like the following that occur when there is an '@' symbol in the previously released `upstream/:{version}` value.
```
git-bloom-import-upstream /tmp/tmpc250f3nv/upstream-0.0.8@baz.tar.gz  --release-version 0.0.10@baz --replace
+++ Cloning working copy for safety
Traceback (most recent call last):
File "git-bloom-import-upstream", line 11, in <module>
load_entry_point('bloom', 'console_scripts', 'git-bloom-import-upstream')()
File "bloom/commands/git/import_upstream.py", line 398, in main
args.replace)
File "bloom/commands/git/import_upstream.py", line 291, in import_upstream
version_check(version)
File "bloom/commands/git/import_upstream.py", line 88, in version_check
.format(last_tag)))
File "bloom/logging.py", line 356, in fmt
msg = t.substitute(_ansi) + ansi('reset') …
```

Escape '@' symbol if present in version tag

---

CHANGELOG.rst
setup.py

This commit should be fast-forwarded rather than merged via GitHub.
The 0.9.0 release has two significant changes: ament (ROS 2) support for RPM spec generation and support for the `ROS_PYTHON_VERSION` dependency conditional.
With the latter change, bloom will generate an error when releasing any package into a rosdistro with no `python_version` defined in the rosdistro index. This is intentional, see #551 for the rationale.

Prepare 0.9.0

---

bloom/commands/release.py

The `--pretend` flag is meant to simulate a release without pushing to the release repo. Since no new content will be pushed during a pretend release the PR created would be invalid and is unexpected.
Closes #549

Don't create a pull request if running with --pretend.

---

setup.py
stdeb.cfg

[Some](https://answers.ros.org/question/341427) [users](#issuecomment-573302415) reported problems with bloom after the introduction of the `test_abi` key in https://github.com/ros-infrastructure/rosdistro/pull/147. In order to be sure that upgrades of bloom use the correct rosdistro, this PR changes dependencies to pull the `0.8.0` version which implements the `test_abi` parsing.
After merging we probably need to create a new release of bloom.

Depend on rosdistro 0.8.0 to solve problems with test_abi key

---

.travis.yml

CI is failing on python 3.4 because the new version of PyYAML dropped support.

Resolve PyYAML Python 3.4 support in CI

---

stdeb.cfg

What will we need to do after merging this? Rerun our `deb` and `deb3` jobs? Or do we need a new release entirely?

add debinc to allow our version to override the upstream version

---

bloom/generators/rpm/generator.py

Unlike debian codenames, RPMs are identified by their version number. Since a number doesn't clarify what OS name it is associated with, the output may be confusing.
This change clarifies the OS name when printing the OS version for RPMs.

Print the OS name along with OS version for RPMs

---

bloom/generators/rosrpm.py
bloom/generators/rpm/generator.py
bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

There is nothing that will currently take advantage of these virtual packages, but providing them now would allow us to implement a mechanism to take advantage of them in the future without re-blooming everything.
The virtual packages which an RPM package provides are not generally exposed in any package lists, so this shouldn't cause any confusion to end users. If merged, you could view this as a "present but disabled" feature.
The motivations for making this change right now, despite being incomplete, are:
* It could save us from requiring re-blooming later on
* It could be used to test a more complete solution at-scale
* It does not change the existing behavior of the packages at all
* Since the functionality described by these virtual packages are, in practice, provided by the …

Provide -devel, -doc and -runtime virtual packages in RPM

---

bloom/generators/rosrpm.py

As it stands, RTI Connext is not available in an RPM package, so this dependency isn't applicable.

Drop Connext from RPM RMW list

---

bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

We can use this RPM macro to optionally append a build stamp to the release version at build time. This is necessary to achieve the same non-abi-compatible scheme as is used in the ROS debian packages.
I've been using another method to suffix the timestamps, but this way is significantly cleaner.

Add an optional release version suffix to RPM templates

---

bloom/generators/rosrpm.py
bloom/generators/rpm/generator.py
bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

This is not a complete implementation of group support in RPMS. The package.xml format does not currently contain enough information for us to specify the specifics of a group dependency. However, we do have enough information to express membership.
Nothing will automatically take advantage of this new group membership information right now, but it will open the door to a mechanism in the future without re-blooming all group members. If merged, you could view this as a "present but disabled" feature.
The motivations for making this change right now, despite being incomplete, are:
* It could save us from requiring re-blooming later on
* It could be used to simplify our existing ad-hoc patching in specific cases
* It could be used to test a more complete solution at-scale
* It does not …

Provide group membership information in RPM packages

---

bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

This off-by-default flag will suppress the automatic call to `rosdep update` at the beginning of each generator.
Note that answering 'y' to a rosdep resolution failure prompt will still trigger a call to `rosdep update`, this flag only suppresses the automatic one.

Suppress automatic rosdep with BLOOM_SKIP_ROSDEP_UPDATE

---

bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

If the user specified the `--non-interactive` command line argument, don't prompt for rosdep key corrections. Instead, exit with an error message.

If not interactive, don't prompt to fix broken rosdep keys

---

bloom/generators/rosrpm.py
bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

Rather than hard-code the circumstances under which weak RPM dependencies are not supported, allow the RPM build configuration to disable them by passing `--without weak_deps` during the RPM build.

Add option to disable weak RPM dependencies

---

bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

This was causing it to be impossible to release with a rpm dependency missing. 
This is fixing the return code triggered in #573 so that the higher level can catch it.

Restore return code of rosdep failure for non-interactive

---

bloom/commands/git/release.py

I had an issue this morning where I couldn't figure out why bloom was picking the previous version for re-releasing, instead of the new one. Found that for some reason the branch to pick melodic releases was still set to kinetic. One can of course go and investigate this in the release repos but in my opinion it's much quicker and cleaner if `bloom` tells us which branch it's determining the new version from.

Print devel branch for version detect

---

CHANGELOG.rst
setup.py

Opening to verify the release candidate for CI. If CI comes back positive the commit in this PR will be fast-forwarded to master and tagged as 0.9.4.

Prepare 0.9.4

---

bloom/commands/git/release.py

The changes in #577 restored an interactive prompt that wasn't
functioning when #581 was being worked on. This checks for interactivity
before running the 'maybe_continue' prompt.

Fix interactive prompt when running non-interactively.

---

bloom/generators/rosdebian.py

Since Foxy has exchanged the rmw vendor OpenSplice for CycloneDDS (which
uses the introspection typesupport) these packages are unavailable after
Foxy. They'll only be added when releasing a distribution known to
contain them. Specifically Bouncy, Crystal, Dashing, and Eloquent.
I tested this PR on Foxy with an unpushed release of rmw_dds_common and verified that the dependency on opensplice was removed. I also tested that I didn't break Dashing and Eloquent releases with an unpushed release of rcl_interfaces into Dashing which does still have the opensplice dependencies as desired.

Update vendor typesupport dependencies for Foxy.

---

bloom/generators/rosdebian.py
bloom/generators/rosrpm.py

They are not needed from Foxy onwards. The requirement was removed in https://github.com/ros2/rosidl_typesupport/pull/62.
I'm not sure of the best way to test this change, confirming that they are indeed not actually needed. I've bloomed *rmw_dds_common* with this change, which was blocked previously because of a circular dependency with *rmw_fastrtps_cpp*: https://github.com/ros/rosdistro/pull/24704
Looking at the resultant deb, it looks like the expected typesupport libraries are installed:
```
librmw_dds_common.so
librmw_dds_common__python.so
librmw_dds_common__rosidl_generator_c.so
librmw_dds_common__rosidl_typesupport_c.so
librmw_dds_common__rosidl_typesupport_connext_c.so
librmw_dds_common__rosidl_typesupport_connext_cpp.so
librmw_dds_common__rosidl_typesupport_cpp.so …
```

Remove RMW implementations from vendor typesupport dependencies

---

bloom/generators/rpm/templates/cmake/template.spec.em

This shouldn't make any difference to a non-catkin package, and aligns with the plain CMake debian template.

Drop CATKIN_BUILD_BINARY_PACKAGE from cmake RPMs

---

bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

It seems that the conditional logic was only getting applied to the conflicts and replaces keys to prevent resolution, but the condition isn't checked when adding the relationship to the package, resulting in a KeyError when a resolved name for the target package isn't available.
This change treats the conflicts and replaces lists the same way as the run and build dependencies.

Fix conditional evaluation of Conflicts/Replaces

---

bloom/generators/rosrpm.py
bloom/generators/rpm/generator.py

There are going to be circumstances where we're going to need to skip a rosdep key in Bloom when either:
1. The dependency isn't available for the target RPM distro but isn't _strictly_ required.
2. The dependency isn't available and we can patch the package to no longer require it.
3. The "group" dependency was hard-coded and doesn't apply to the target RPM distro.
Without this option, there isn't a way to get bloom to the patching stage of generation without overriding the entire `package.xml` with an overlay or patching in the `release/foo/bar` stage, both of which would affect debian generation as well.
A prime example of this is `python3-pep8` on Eloquent, which can be patched to use `python3-pycodestyle` instead. Another is `rmw_connext_cpp`, where Connext isn't available at all in …

Add --skip-keys argument to the RPM generator

---

bloom/config.py

The default distribution for the RPM generator is Fedora. Since we're going to start generating RPMs for RHEL/CentOS, we need to update the template to perform generation for that platform specifically.

Add RHEL to the default action list

---

bloom/generators/debian/templates/ament_cmake/rules.em
bloom/generators/debian/templates/cmake/rules.em

This CMake variable is already set for the `catkin` template, but is not currently set for the `ament_cmake` and plain `cmake` templates.
The `CMAKE_INSTALL_PREFIX` variable seems to be sufficient to allow CMake to find packages which are installed under that path, however when a package is present in a system location as well as under the target installation prefix, preference is given to the system package (given that it satisfies any version requirements specified).
Setting `CMAKE_PREFIX_PATH` should give preference to the packages under that path when a package is also available as a system package and both satisfy any version requirements.
Note that the RPM templates are already using `CMAKE_PREFIX_PATH` in this way.
This is motivated by some internal discussions at Open Robotics, …

Add CMAKE_PREFIX_PATH to ament_cmake and cmake templates

---

bloom/generators/debian/templates/cmake/rules.em

I want to discuss whether this patch is acceptable or, on the contrary, packages are enforced in ROS *not* to use multiarchs lib prefixes. In the latter case, it would be great to have this documented somewhere, if it's not already. 
Thanks!
Pros: Any 3rd party library, well-behaved in the Debian sense of implementing multiarch prefixes, would be automatically release-able via bloom w/o changes...
Cons: none?
See: 
- https://www.ros.org/reps/rep-0136.html
- https://answers.ros.org/question/356962/should-cmake_install_libdir-be-ignored-in-rep136-packages/
- https://github.com/MRPT/mrpt/issues/1076
- Maybe related? https://answers.ros.org/question/290073/problem-building-with-non-installed-dependencies/
- Maybe related? https://www.ros.org/reps/rep-0122.html#lib

Solve shlibdeps errors in REP136 packages that use GNUInstallDirs.

---

CHANGELOG.rst

I think this might have been an oversight when updating the changelog? The fork urls all 404 since the relevant issues/PRs are on the primary fork.

Update changelog urls which were pointing to a fork.

---

.travis.yml
test/system_tests/test_catkin_release.py
test/utils/common.py

The idea here is to decouple Bloom from the live rosdistro index and rosdep database. This will also isolate bloom from the rosdep state that the system has, and makes the tests function without any network access. Since the system rosdep state isn't a dependency any more, the tests can be run even if 'rosdep init' has not been invoked on the system, meaning that the tests can now be executed without sudo rights.
This change also significantly reduces the time it takes to run the tests. Part of that is due to the `BLOOM_SKIP_ROSDEP_UPDATE` value, which suppresses Bloom's automatic rosdep update invocation. This isn't necessary for the 'fake' rosdep cache to work, but it makes things a bit quicker.
This change is motivated by the tests currently failing due to ros/rosdistro#27640. Rather …

Create and use a 'fake' rosdep cache for tests

---

.github/workflows/ci.yaml
.travis.yml

Uses GitHub Actions for CI to take some of the weight off of Travis. Travis is still used for Python 3.4 support.

Use GitHub Actions for CI

---

test/utils/common.py

Resolves 'SyntaxWarning: "is not" with a literal'

Fix some syntax warnings with literal comparisons

---

bloom/generators/rosdebian.py
bloom/generators/rosrpm.py

The most common patching error I've seen in Bloom repositories manifests from carrying forward a patch from a previous track to a new one, when that patch has a hard-coded ROS distribution name in it. Unfortunately, this error often goes unnoticed when the patch modifies the weak dependencies of a package.
This substitution will allow us to roll the patches forward unmodified.

Add a template substitution for the ROS distro

---

bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

The multiarch story has changed quite a bit since I set CMAKE_INSTALL_LIBDIR back in 2015. In particular, the ability to package plain CMake packages means that we've been forced to accept the presence of library directories other than 'lib' in ROS.
This change removes the CMAKE_INSTALL_LIBDIR override and lets GNUInstallDirs instruct some packages to use 'lib64'. A typical ROS package will still install directly to 'lib'.
One of the cases driving this removal is the vendor package pattern in ROS 2, where the CMAKE_INSTALL_LIBDIR override is not passed through from the vendor package to the external project it's wrapping, so override isn't working in all cases. Better to let the library directory differ and individually fix the packages that are misbehaving, like the one that originally …

Align CMake args in RPMs with debs

---

bloom/commands/git/config.py
bloom/config.py

This change makes the prompt to reset the actions list a little less aggressive, specifically when the actions list is 'custom' and doesn't match any of the historical defaults.

Only suggest resetting action list if it's old

---

bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

The `CTEST_OUTPUT_ON_FAILURE` environment variable can be used to get more information on test failures. Since it is an environment variable, it is unlikely to affect non-CTest tests that can be run when `make test` is invoked.

Enable output from CTest failures in RPMs

---

bloom/generators/rosrpm.py

Connext isn't available in RPM form, so that RMW isn't supported in RPM packages for ROS.

Drop Connext from typesupport dependencies for RPMs

---

bloom/generators/rosdebian.py

Up to foxy, the connext RMW required typesupport packages.
Starting in Galactic, the new connext RMW no longer requires
those packages.  Revamp the logic here so that we only add
those connext typesupports for distros before Galactic.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
@nuclearsandwich @cottsay This is part of https://github.com/rticommunity/rmw_connextdds/issues/9 .  I'm not quite sure how to test it, so any hints there are welcome.  Also, once we merge this we'll really need a new bloom release so that we can re-release all of the interface packages into Rolling/Galactic to remove this dependency.

Rewire the typesupport dependencies for post-Foxy.

---

bloom/github.py

New personal access tokens on GitHub are not created as oauth tokens and
are not usable with token authentication. Instead they're used as the
password for basic authentication.
More info on these new tokens is in [this GitHub blog post](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/).
This is a minimal change to ensure that bloom can continue to work with
these new tokens.

Use basic authentication with new personal access tokens.

---

bloom/commands/release.py

The ros/rosdistro repository has accumulated many forks and the current
bloom strategy of listing them all then finding the one belonging to the
current GitHub user takes time.
Most of the time a forked repository has the same name as the parent.
This PR checks that the target repository and a user repository with the
same name (if it exists) share the same "source" and are thus in the
same fork network so pull requests can be created between them.
If the fork exists with the right name this check is now almost
instantaneous on my local internet connection so this could save a lot
of seconds when working on releases to ros/rosdistro and since it
creates only two additional API requests it should not slow down the
exhaustive search by very much.

Add a fast check for the likely fork name.

---

bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

It's far more common to use patch level 1 in RPMs, mainly because that's the default patch level that the unified diffs produced by git use.
Merging this would mean one fewer change to make when debugging RPM issues locally using 'rpmbuild'.
I know that template changes can sometimes result in patching failures - making changes like this that reduce development friction while relatively few ROS 2 packages have been generated by the community is worth 1 or 2 merge conflicts.

Specify patch level for RPMs

---

bloom/github.py

Since multi-factor authentication has become paramount for GitHub and
similar sites I hope that most of Bloom's users encounter the failure to
automatically create a token on their behalf.
This updates the authentication failure mode to provide instructions for
creating a token via the GitHub web UI and copy it into Bloom's
configuration.
The authorizations API previously used by bloom is not documented
currently so I didn't have a reference for trying to continue using it
with MFA.
This PR includes #627 and if that merges I'll rebase this PR so this PR can be reviewed independently.

Collect manually created token rather than attempting to create one.

---

CHANGELOG.rst
setup.py

- Use basic authentication with the new personal access tokens. #627
- Add a fast check for the likely fork name. #629
- Specify patch level in RPM templates. #626
- Collect manually created token rather than attempting to create one. #628
If approved this PR should be fast-forwarded rather than squashed.

Prepare 0.10.4 release.

---

bloom/github.py

The new personal access tokens from GitHub for which support was first
added in bloom in #627 use basic authentication like a username and
password rather than the OAuth token authentication used by OAuth tokens
and previous iterations of the personal access token. When adding
support for this it seems like I missed a trick and as a result the
authentication header was being sent as
`Basic b'base64encodeduserandtoken'` rather than
`Basic base64encodeduserandtoken`.
I have to do an experimental bisect to determine why this issue is only
showing up now. Perhaps it's been an issue since the jump to python3 but
since basic authentication was only ever used as a springboard for token
auth it was overlooked when reported.
I am pretty sure that this will address #632 as well as tokens being …

Fix token authentication error.

---

bloom/commands/git/patch/import_cmd.py

It seems that git's 3-way merge is a bit more forgiving than the default 'clean application' approach. Specifying this option will attempt a 3-way merge to apply the patch only after a patch doesn't apply cleanly.
This seems to have eliminated some manual patch application on at least a couple of repositories during the galactic branching process.

Fall back to 3-way merge when applying patches

---

bloom/generators/debian/generator.py
bloom/generators/debian/templates/ament_cmake/copyright.em
bloom/generators/debian/templates/ament_python/copyright.em
bloom/generators/debian/templates/catkin/copyright.em
bloom/generators/debian/templates/cmake/copyright.em
test/system_tests/test_catkin_release.py

This should be a reasonable starting place for supporting machine-readable debian/copyright files in the debian generator. Manifests which utilize the 'file' attribute in their 'licence' elements should end up with their LICENSE text in the debian/copyright file as before, but now the file will be formatted according to [Debian Policy 4.6.0.1](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/).
Fixes #645

Machine-readable debian/copyright file

---

bloom/generators/rpm/generator.py
bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/ament_python/template.spec.em
bloom/generators/rpm/templates/catkin/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

Following the Fedora guidelines, multiple licenses can be expressed in the `License` field: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Multiple_Licensing_Scenarios
We can also include the actual license text files if they are listed in the package manifest - a feature introduced in the manifest specifications v3.
Note that this will cause a new build failure if the file referenced by the manifest is not present.

Include more license information in RPM spec files

---

.github/workflows/ci.yaml
stdeb.cfg

https://wiki.ubuntu.com/Releases#List_of_releases
- Xenial:  Apr 2021
- Yakkety: Jul 2017
- Zesty:   Jan 2019
- Artful:  Jul 2018
- Cosmic:  Oct 2018
- Disco:   Apr 2019
- Eoan:    Oct 2019
Should we consider dropping Jessie as well? https://www.debian.org/releases/

Drop support for EOL Ubuntu distros

---

setup.py

It seems that this dependency actually uses an underscore in the package name, but it typically "just works" because pip normalizes it.
https://github.com/ros-infrastructure/catkin_pkg/blob/52f0a367733e4e161622d4f205ce95ed8ec8c164/setup.py#L19
Motivation for this change is that colcon doesn't currently support the "loose" name comparison that pip employs.

Un-normalize catkin_pkg dependency name

---

bloom/commands/git/patch/import_cmd.py
bloom/commands/git/release.py

If git-bloom-release is run non-interactively then that should be
propagated to the actions command so that actions are not blocked on
interactivity.
This patch uses an environment variable to send that message since the action commands do not have a --non-interactive flag and their command-line arguments are all defined statically in the tracks file so using the environment makes more sense than further munging those tracks unless we consider adding a {non-interactive} template to the tracks string, which would require updating all outstanding tracks files, also not my favorite idea.
I haven't audited the code for additional interactive points inside tracks files and I'm not yet sure if I mean to or if I plan to play "whack-a-mole" with them as I find them naturally over time.

Exit early on patch failure if bloom is being run non-interactively.

---

stdeb.cfg

Drop Debian Jessie and Stretch from all releases.
Add Ubuntu Jammy and Debian Bullseye to python3 releases.

Update release suites for bloom.

---

docs/index.rst

Both the recommended ROS1 version (Noetic) and recommended ROS2 version (Galactic) target Ubuntu Focal (20.04). On 20.04, the correct apt-install is actually `python3-bloom`: the current documentation specifies `python-bloom`, which is unavailable and fails. This merge updates the installation instruction to reflect this change.

Update package apt install

---

bloom/commands/generate.py

When ``bloom-generate`` is called without arguments, this now shows:
```sh
usage: bloom-generate [-h] [debian | rosdebian | rosrpm | rpm] ...
bloom-generate: error: the following arguments are required: [debian | rosdebian | rosrpm | rpm]
```
Rather than continuing without an argument and causing an unrelated error:
```sh
/home/russ/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
warnings.warn(
/home/russ/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
warnings.warn(
Traceback (most recent call last):
File "/usr/bin/bloom-generate", line 33, in <module> …
```

ensure subparser is required

---

bloom/commands/release.py

If you are adding a new repository to rosdistro, it will prompt you to add Documentation and Source information, but it will not use any of the information previously used to fill in the defaults. This PR uses the `track_dict` object to populate the defaults for the fields. 
So instead of 
```
Would you like to add documentation information for this repository? [Y/n]? 
==> Looking for a doc entry for this repository in a different distribution...
No existing doc entries found for use as defaults.
Please enter your repository information for the doc generation job.
This information should point to the repository from which documentation should be generated.
VCS Type must be one of git, svn, hg, or bzr.
VCS type: git
VCS url: https://github.com/MetroRobots/ros_system_fingerprint.git
VCS …
```

Add Defaults for src/doc information

---

bloom/commands/release.py
stdeb.cfg

Currently, a maintainer must initialize a release repository before running bloom (such as by adding a README.md). If a release repository is uninitialized, bloom will complain such as:
```sh
==> git push --dry-run
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream origin master
Cannot push to remote release repository.
```
The change in this PR makes bloom work with uninitialized remote repositories. (Hence alleviating the need to manually initialize)
Apart from this ``git push --dry-run`` command that was failing, bloom seems to be able to work with an uninitialized remote repository completely fine.
Resolves: ros2-gbp/ros2-gbp-github-org#47
Signed-off-by: Kenji Brameld <kenjibrameld@gmail.com>

Dry-run with set-upstream origin master, in case remote repo isn't initialized yet

---

.github/workflows/ci.yaml
bloom/commands/git/import_upstream.py
bloom/commands/release.py
bloom/commands/update.py
bloom/generators/debian/generator.py
bloom/generators/release.py
bloom/git.py
bloom/logging.py
bloom/rosdistro_api.py
setup.py

Resolves: #678.
Switch to packaging since use of pkg_resources is discouraged. Related: https://github.com/pypa/setuptools/issues/2497
Also:
* Uses regex to do version matching, because packaging's version parsing is a lot more strict about version numbers.
* Also, removes a check for whether a mac is Mountain Lion or greater and just changes it to a check for whether it is a mac.

Replace pkg_resources.parse_version with packaging.version.parse

---

stdeb.cfg

This was introduced in #693 and I realized that it needed the stdeb dependency while I was on a walk but forgot to add that before re-reviewing and merging that PR.
This package is available for Python 2 in [Buster](https://packages.debian.org/buster/python3-packaging) and [Bionic](https://packages.ubuntu.com/bionic/python-packaging).
As well as for Python 3 in [Buster](https://packages.debian.org/buster/python3-packaging) and [Bionic](https://packages.ubuntu.com/bionic/python3-packaging) and later distributions.

Add debian dependency to stdeb.cfg for new packaging dependency.

---

.github/workflows/ci.yaml

In order to keep track of regressions due to drift / bitrot versus regressions introduced by new PRs.
Answering the question of why 7:40 UTC on Sundays which was raised by @ijnek:
The clock for scheduled actions in GitHub Actions uses UTC so 07:40 UTC is 11:40 / 00:40 US Pacific which means.
Kind of no reason. GitHub Actions lacks the cron syntax extension for picking a single random value within the field (something Jenkins does with its `H` value) in order to spread scheduled build load out across the hour. 0 and 30 are the most commonly used times so I just shifted slightly from that.
It's the first night of the workweek which means that we can show up Monday morning and see whether the previous week brought any new issues to CI. In terms of vague "workweek" notions the objective of …

Add weekly scheduled run to make sure that CI stays green.

---

.github/workflows/ci.yaml
setup.cfg
setup.py

* Switch to extras_require.test
* Pin to empy < 4
* Switch to unified ros-infrastructure CI
Note that Bloom tests are broken with Python 3.10+, so I'm excluding that from CI in favor of a followup fix. This PR is intended simply to get the train moving again.

Modernize CI

---

test/__init__.py
test/fake_rosdistro/index-v4.yaml
test/fake_rosdistro/melodic/distribution.yaml

The tests currently require the rosdistro index to be reachable.

Create a fake rosdistro index for better test isolation

---

.github/workflows/ci.yaml
bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py

The configparser.SafeConfigParser class was renamed to ConfigParser in Python 3.2. In Python 3.10, it was finally removed.
The import was copy/pasted from the debian generator to the RPM generator, but isn't actually used there and could be removed.

Switch from SafeConfigParser to ConfigParser

---

stdeb.cfg

Following in the wake of catkin_pkg, we're dropping python2 support now that it's no longer the default on any active distribution.
Dropped:
* Ubuntu Bionic (18.04 LTS)
* Debian Buster (oldoldstable)
* Debian Bullseye (oldstable)
Added:
* Ubuntu Noble (24.04 LTS pre-release)
* Debian Trixie (testing)
Retained:
* Ubuntu Focal (20.04 LTS)
* Ubuntu Jammy (22.04 LTS)
I have also raised the minimum python3 version to 3.6 as we are only testing back to 3.6 and RHEL 8 has the oldest python distribution (3.6) of any supported platform.
#723 updates the CI platforms targeted by bloom.
Ref: https://github.com/ros2/ros2/issues/1511

Update deb platforms and drop python2 packaging.

---

bloom/generators/debian/generator.py
bloom/generators/rpm/generator.py
docs/bump_version.py
test/system_tests/test_catkin_release.py
test/utils/package_version.py

Should avoid `SyntaxWarning: invalid escape sequence`

Use raw strings for regular expressions

---

MANIFEST.in
setup.py

The setuptools documentation states that `package_data` is used for finer-grained control over the inclusion of package data as an alternative to `include_package_data`/`MANIFEST.in`. After correcting the glob patterns in `package_data`, the latter mechanisms are no longer needed.
Docs: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#configuration-options
Should alleviate warnings like this:
```
/usr/lib/python3.12/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'bloom.generators.rpm.templates.cmake' is absent from the `packages` configuration.
!!
********************************************************************************
############################
############################
Python recognizes 'bloom.generators.rpm.templates.cmake' as an …
```

Fix template file inclusion in Python package

---

bloom/generators/debian/templates/ament_cmake/rules.em

It seems that `dh_shlibdeps` needs to know about each location where shared object libraries are installed so that it knows which libraries are provided by a package. This is particularly important information in the context of multiple inter-linked libraries within a single package.
The `ament_vendor` macro provided by `ament_cmake_vendor_package` installs to the `opt/{package_name}` sub-tree, so we should search for dynamic libraries there as well.
https://man7.org/linux/man-pages/man1/dh_shlibdeps.1.html

Add dh_shlibdeps entry for libraries installed by ament_vendor

---

bloom/commands/generate.py

Addresses https://github.com/ros-infrastructure/bloom/pull/683#issuecomment-1493301856

Fix regression in RHEL 8 / Python3.6 support.

---

bloom/generators/rosrpm.py

The default 'installation_prefix' is '/usr'. This is wrong for 'rosrpm' and has to be prefixed correctly with the default ROS installation.
With a "standard" bloom pipeline for RPM with something like:
```sh
dnf install python3-bloom
git clone https://github.com/AprilRobotics/apriltag.git
cd apriltag
bloom-generate rosrpm --ros-distro humble
dnf builddep -y rpm/template.spec
rpmbuild -bb --build-in-place rpm/template.spec
```
I am getting spec files with `@(InstallationPrefix)` set to `/usr`:
```spec
%build
if [ -f "/usr/setup.sh" ]; then . "/usr/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
-UINCLUDE_INSTALL_DIR \
-ULIB_INSTALL_DIR \
-USYSCONF_INSTALL_DIR \
-USHARE_INSTALL_PREFIX \
-ULIB_SUFFIX \
-DCMAKE_INSTALL_PREFIX="/usr" \ …
```

fix ROS installation prefix for RPM generator

---

bloom/generators/rpm/templates/ament_cmake/template.spec.em
bloom/generators/rpm/templates/cmake/template.spec.em

The RPM CMake macros under `/usr/lib/rpm/macros.d/macros.cmake` are defined differently for RHEL / AlmaLinux 8 and 9. Specifically, under AlmaLinux 8 in-source builds are enabled via `%__cmake_in_source_build 1` and AlmaLinux 9 turns of stripping via `-DCMAKE_INSTALL_DO_STRIP:BOOL=OFF`.
The effect is that the evaluation of the macros generates different spec files. This can be verified via:
```sh
docker run --rm almalinux:8 bash -c "dnf -y install cmake && rpm --eval '%cmake' && rpm --eval '%cmake_build'"
docker run --rm almalinux:9 bash -c "dnf -y install cmake && rpm --eval '%cmake' && rpm --eval '%cmake_build'"
```
On AlmaLinux 8 this evaluates to:
```spec
%if 0 
%set_build_flags 
%else 
CFLAGS="${CFLAGS:--O2 -g}" ; export CFLAGS ; 
CXXFLAGS="${CXXFLAGS:--O2 -g}" ; export CXXFLAGS ; …
```

use CMake rpm macros and unset in-source builds

---

CHANGELOG.rst
setup.py

Principally includes meson support and some smaller python changes. I decided to proceed rather than wait for #747 but could be convinced to fold that in too.

Prepare 0.13.0 release.
